import subprocess
from pathlib import Path
import sys
#TODO: in future build_extraction_package() and normalize_extracted_markdown() eventually
def validate_marker_paths(
    source_pdf: Path,
    output_dir: Path,
) -> tuple[Path, Path]:
    """Validate and prepare the paths required for Marker extraction."""

    source_pdf = source_pdf.expanduser().resolve()
    output_dir = output_dir.expanduser().resolve()

    if not source_pdf.is_file():
        raise FileNotFoundError(
            f"Source PDF does not exist: {source_pdf}"
        )

    if source_pdf.suffix.lower() != ".pdf":
        raise ValueError(
            f"Source file is not a PDF: {source_pdf}"
        )

    if output_dir.exists() and not output_dir.is_dir():
        raise NotADirectoryError(
            f"Marker output path is not a directory: {output_dir}"
        )

    if output_dir.exists() and any(output_dir.iterdir()):
        raise FileExistsError(
            f"Marker output directory is not empty: {output_dir}"
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    return source_pdf, output_dir


def run_marker(
    source_pdf: Path,
    output_dir: Path,
    *,
    marker_executable: str = "marker_single",
    output_format: str = "markdown",
    paginate_output: bool = True,
) -> subprocess.CompletedProcess[str]:
    """Run Marker and capture its console output."""

    command = [
        marker_executable,
        str(source_pdf),
        "--output_dir",
        str(output_dir),
        "--output_format",
        output_format,
    ]

    if paginate_output:
        command.append("--paginate_output")

    return subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )


def marker_logger(
    completed: subprocess.CompletedProcess[str],
    output_dir: Path,
    *,
    log_console: bool = False,
    log_errors: bool = True,
) -> Path | None:
    """Print Marker output optionally and write a log only after failure."""

    if log_console:
        if completed.stdout:
            print(completed.stdout)

        if completed.stderr:
            print(completed.stderr, file=sys.stderr)

    if completed.returncode == 0 or not log_errors:
        return None

    error_log = output_dir / "marker_error.log"

    error_log.write_text(
        f"Command: {completed.args}\n"
        f"Return code: {completed.returncode}\n\n"
        f"STDOUT:\n{completed.stdout}\n\n"
        f"STDERR:\n{completed.stderr}\n",
        encoding="utf-8",
    )

    return error_log


def collect_generated_files(
    output_dir: Path,
) -> tuple[Path, ...]:
    """Collect files generated by Marker."""

    excluded_files = {
        output_dir / "marker_error.log",
    }

    generated_files = tuple(
        sorted(
            path
            for path in output_dir.rglob("*")
            if path.is_file() and path not in excluded_files
        )
    )

    if not generated_files:
        raise RuntimeError(
            f"Marker generated no files in: {output_dir}"
        )

    return generated_files


def run_pdf_preparation_pipeline(
    source_pdf: Path,
    output_dir: Path,
    *,
    log_console: bool = False,
) -> tuple[Path, ...]:
    """Run the current PDF preparation pipeline."""

    source_pdf, output_dir = validate_marker_paths(
        source_pdf,
        output_dir,
    )

    completed = run_marker(
        source_pdf,
        output_dir,
    )

    error_log = marker_logger(
        completed,
        output_dir,
        log_console=log_console,
    )

    if completed.returncode != 0:
        raise RuntimeError(
            f"Marker extraction failed. Error log: {error_log}"
        )

    return collect_generated_files(output_dir)